### PR TITLE
Use Expectation constructor (fixes #30)

### LINKED ISSUE #30: Visibility issue in Expectation extension
The workaround for accessing making the `Expectation` constructor "public" doesn't seem to work (anymore?):

```
extension Expectation {
    init(_ expression: Expression<T>) {
        self.expression = expression
    }

    // ...
}
```

I get the following error:

> Initializer for struct 'Expectation<T>' must use "self.init(...)" or "self = ..." because it is not in module 'Nimble'

I raised https://github.com/Quick/Nimble/pull/531 - if that gets merged, I'll try to put up a PR to just use the constructor.

### PR DESCRIPTION
**Pull request by mrcljx**
Depends on https://github.com/Quick/Nimble/pull/531

See #30 for more info.

### CODE REVIEW

**Review by ashfurrow — APPROVED** [review]
Good work! We can merge once the other PR is merged + released.

**Comment by mrcljx** [comment]
@ashfurrow I changed it to be a backward-compatible change (assuming that RxNimble was unusable with Swift 4.1+) so that we could land this without waiting for Nimble to release a new version.

**Comment by mrcljx** [comment]
Sorry for the chaotic commit log - squash it, if possible. 😇

**Comment by ashfurrow** [comment]
I think we'll have to wait for that Nimble PR to get released (it's merged, but not released).

**Comment by mrcljx** [comment]
Since RxNimble is unusable for Swift 4.1+ users, I think this theoretically could be merged already (and even be released as a .1) to automatically benefit once the next Nimble version is released (whether to bump the dependency and release a new minor version could be a separate decision/step).

But completely at your discretion. 👍

**Comment by ashfurrow** [comment]
Makes sense, I'll try to get this released today (if someone else is able to, that'd be a huge help!).

File: Source/Expectation+Ext.swift [hunk 1]
```diff
@@ -1,12 +1,19 @@
 import Nimble
 
 extension Expectation {
+    #if swift(>=4.1)
```
Comment (ashfurrow) [inline Source/Expectation+Ext.swift:4]: Are we sure this shouldn't be `4.2` instead? Xcode 9 shows Swift version is 4.1.2, but Xcode 10 beta shows 4.2. I got a validation error while pushing to CocoaPods because of this, which I'm fine circumventing as long as this is correct 👍

Comment (ashfurrow) [reply Source/Expectation+Ext.swift:4]: Nah, never mind you're right. Hmm, I guess the validation won't be fixed until there's a new Nimble release with the public constructor. I'll wait on that.

In the meantime, anyone can point their Podfile to this repo's `master` branch to use this change right away 👍

Comment (ashfurrow) [reply Source/Expectation+Ext.swift:4]: Hmm, then why is CI working but my local Xcode 9 isn't? https://travis-ci.org/RxSwiftCommunity/RxNimble/jobs/391941472

**Comment by ashfurrow** [comment]
Okay, still no Nimble release. I'm about to go on vacation so I won't be around to release this for a few weeks, FYI.

**Comment by mrcljx** [comment]
Enjoy your vacation. 👋 I'm sure we can do some Nimble master pinning while you relax. 😉

**Comment by ashfurrow** [comment]
I went to release this but have run into a problem. I've opened an issue with Nimble and hope to hear back soon: https://github.com/Quick/Nimble/issues/575

**Comment by ashfurrow** [comment]
Okay! It's been a while but this has been released as RxNimble 4.2.0. The commit is here: https://github.com/RxSwiftCommunity/RxNimble/commit/a9e2d270784e2c0c8b611b3d5c4ced733d7b166f It should be available on CocoaPods and Carthage. Thanks again!
